### ISSUE TITLE
private method `new' called for Jekyll::AmazonResultCache:Class

### ISSUE THREAD

**Issue by klein0r** [longkey1/jekyll-amazon-plugin#6]
Thank you for the plugin but i get the following exception when serving:

```
jekyll 3.0.0 | Error:  private method `new' called for Jekyll::AmazonResultCache:Class
```

Is your plugin jekyll 3.0 ready?

**Comment by longkey1** [comment]
I confirmed that this plugin works on Jekyll 3.1.2.

**Comment by tksohishi** [comment]
It happened when there is _site in _plugins/amazon directory, which is created when you accidentally run `jekyll bulid` or `jekyll serve`. Removing _site should fix this issue.

**Comment by longkey1** [comment]
@tksohishi 

Thanks for report!
I could not simulate the situation that `_site` directory was created in the  `_plugins/amazon` directory...

**Comment by tksohishi** [comment]
Hmm, weird...

**Comment by enkota** [comment]
Hey @tksohishi did you ever fix this? I just tried to setup on my site and getting the same error!

**Comment by klein0r** [comment]
🤷‍♂️
